version: 2
jobs:
  test:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Download and install tflint
          command: |
            wget https://github.com/wata727/tflint/releases/download/v0.5.4/tflint_linux_amd64.zip
            unzip tflint_linux_amd64.zip
      - run:
          name: Lint the terraform code
          command: ./tflint --deep --aws-region eu-west-2
      - run:
          name: Run terraform init
          command: terraform init -input=false
      - run:
          name: Run terraform plan
          command: terraform plan -out=tfplan -input=false
      - persist_to_workspace:
          root: .
          paths:
            - tfplan
  deploy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install dependencies
          command: apk add --update py-pip bash
      - run:
          name: Install aws-cli
          command: pip install awscli --upgrade --user
      - run:
          name: Deploy terraform code
          command: |
            terraform init -input=false
            terraform apply tfplan
      - run:
          name: Update NS and SOA records
          command: /bin/bash scripts/ns.sh
      - run:
          name: Update registrar NS records
          command: /bin/bash scripts/reg.sh
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v[0-9]\.[0-9]\.[0-9]$/
            branches:
              ignore: /.*/
